project_style:
  content_structure:  'simple_book'
  should_register:    false
  get_druid_from:     'container_barcode'
  use_druid_minter:   true

bundle_dir:           'spec/test_data/bundle_input_d'
staging_dir:          'tmp'
accession_items:      ~

manifest:             ~
checksums_file:       ~
desc_md_template:     ~

progress_log_file:    'log/progress_gould.yaml'
project_name:         'Gould'
apo_druid_id:         'druid:sr292kr3857'
set_druid_id:         ~

publish_attr:
  publish:            'no'
  shelve:             'no'
  preserve:           'yes'

compute_checksum:     true
init_assembly_wf:     false

content_md_creation:
  style:              'default'
  pre_md_file:        ~

object_discovery:
  use_manifest:       false
  glob:               '*'
  regex:              '^\d+$'

stageable_discovery:
  use_container:      false
  glob:               '00'
  regex:              ~
      
manifest_cols:
  object_container:   ~
  source_id:          ~
  label:              ~

content_exclusion:    ~

validate_usage:       true
show_progress:        true
limit_n:              10
uniqify_source_ids:   true
cleanup:              true
resume:               false
