# A project which uses a manifest for object discovery, one file per object.

project_style:
  content_structure:  'simple_image'
  should_register:    false
  get_druid_from:     'druid_minter'

bundle_dir:           'spec/test_data/bundle_input_c'
staging_dir:          'tmp'
accession_items:       ~

validate_files:       true

manifest:             'manifest.csv'
checksums_file:       'checksums.txt'
desc_md_template:     'mods_template.xml'

progress_log_file:    'log/progress_reid_dennis.yaml'
project_name:         'ReidDennis'
apo_druid_id:         ~
set_druid_id:         ~

publish_attr:
  publish:            ~
  shelve:             ~
  preserve:           ~

compute_checksum:     true
init_assembly_wf:     false

content_md_creation:
  style:              'default'
  pre_md_file:        ~

object_discovery:
  use_manifest:       true
  glob:               ~
  regex:              ~

stageable_discovery:
  use_container:      true
  glob:               ~
  regex:              ~

manifest_cols:
  object_container:   'file_name'
  source_id:          'stanford_file_id'
  label:              'title1'

content_exclusion:    ~

validate_usage:       true
show_progress:        true
limit_n:              5
uniqify_source_ids:   true
cleanup:              true
resume:               false
