dist: bionic
language: ruby
cache: bundler

sudo: false
notifications:
  email: false

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - ROBOT_ENVIRONMENT=test

rvm:
  - 2.5.3 # default deployed
  - 2.6.4
  - 2.7.1

before_install:
  # Update to latest rubygems -- for ruby 2.5.3
  - yes | gem update --system
  # Get bundler 2.0 for ruby 2.6.4
  # - gem install bundler

bundler_args: --without production deployment
